mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'
urlpatterns = [
    path('', views.home_view, name='homepage'),
    path('notes', views.notes_view, name='notes'),
    path('set-encryption-key', views.set_encryption_key, name='set-encryption'),
    path('passwords', views.passwords_view, name='passwords'),
    path('settings', views.settings_view, name='settings'),
    path('settings/<int:enc_id>', views.change_encryption_key, name='change-key'),

    path('passwords/<int:id>', views.password_view, name='password'),
    path('passwords/<int:id>/decrypt',views.decrypt_password, name='decrypt-password'),

    path('notes/<int:id>', views.note_view, name='note'),
    path('notes/<int:id>/decrypt', views.decrypt_note, name='decrypt-note'),
]

onepass/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('allauth.urls')),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from . import crypting
from django.conf import settings


class CustomUser(AbstractUser):
	pass

class CustomUserManager(UserManager):
	pass

class UserPasswords(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	URL = models.URLField()
	name = models.CharField(max_length=150)
	username_or_email = models.CharField(max_length=150)
	site_password = models.CharField(max_length=150)
	notes = models.TextField()


	class Meta:
		verbose_name_plural = 'User Passwords'
	# def save(self, *args, **kwargs):
	# 	self.site_password = crypting.encryptMessage(UsersEncryptionKey., self.site_password)
	# 	self.notes = crypting.encryptMessage('ASIMOV', self.notes)
	# 	super(UserPasswords, self).save(*args, **kwargs)

	def __str__(self):
		return f'{self.name} - {self.username_or_email}'

class UserCards(models.Model):
	CARDS = (
		('Visa', 'Visa'),
		('Mastercard', 'Mastercard'),
	)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	name_on_card = models.CharField(max_length=150)
	card_type = models.CharField(choices=CARDS, max_length=100)
	card_number = models.IntegerField()
	security_CVV_code = models.IntegerField()
	start_date = models.DateField()
	expiration_date = models.DateField()
	notes = models.TextField()

	class Meta:
		verbose_name_plural = 'User Cards'

	def __str__(self):
		return f'{self.name_on_card} - {self.card_number}'

class UserNotes(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	note_title = models.CharField(max_length=150)
	note_content = models.TextField()

	class Meta:
		verbose_name_plural = 'User Notes'

	def __str__(self):
		return self.note_title


class UsersEncryptionKey(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	enc_key = models.CharField(max_length=50, blank=False, null=False)

	class Meta:
		verbose_name_plural = 'User Encryption Keys'

	def __str__(self):
		return f'{self.user}'

mainapp/forms.py
from django import forms
from .models import UserPasswords, UserCards, UserNotes, UsersEncryptionKey

class UserPasswordsForm(forms.ModelForm):
    widgets = {'user':forms.TextInput(attrs={'readonly':'readonly'})}
    class Meta:
        model = UserPasswords
        
        fields = [
            'URL',
            'name',
            'username_or_email',
            'site_password',
            'notes',
        ]

class UserCardsForm(forms.ModelForm):
    widgets = {'user':forms.TextInput(attrs={'readonly':'readonly'})}
    class Meta:
        model = UserCards
        fields = [
            'name_on_card',
            'card_type',
            'card_number',
            'security_CVV_code',
            'start_date',
            'expiration_date',
            'notes'
        ]

class UserNotesForm(forms.ModelForm):
    widgets = {'user':forms.TextInput(attrs={'readonly':'readonly'})}
    class Meta:
        model = UserNotes
        fields = ['note_title','note_content',]

class UsersEncryptionKeyForm(forms.ModelForm):
    widgets = {'user':forms.TextInput(attrs={'readonly':'readonly'})}
    class Meta:
        model = UsersEncryptionKey
        fields = ['enc_key',]

class changeUsersEncryptionForm(forms.ModelForm):
    widgets = {'user':forms.TextInput(attrs={'readonly':'readonly'})}
    class Meta:
        model = UsersEncryptionKey
        fields = ['enc_key',]

mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from allauth.account.views import SignupView, LoginView
from .forms import UserPasswordsForm, UserCardsForm, UserNotesForm, UsersEncryptionKeyForm, changeUsersEncryptionForm
from .models import UserPasswords, UserNotes, UserCards, CustomUser, UsersEncryptionKey
from django.contrib.auth.decorators import login_required
from . import crypting
from cryptography.fernet import fernet
import time

def home_view(request):
    user_key = UsersEncryptionKey.objects.get(user__id=request.user.id)
    context = {'user_key':user_key}
    return render(request, 'mainapp/index.html', context)

@login_required
def passwords_view(request):
    use_pass = UserPasswords.objects.filter(user=request.user)
    user_key = UsersEncryptionKey.objects.get(user__id=request.user.id)
    if request.method == 'POST':
        form = UserPasswordsForm(request.POST or None)
        userskey = UsersEncryptionKey.objects.get(id = request.user.id)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.user.id = request.user.id
            new_form.site_password = crypting.encryptMessage(userskey.enc_key, new_form.site_password)
            new_form.notes = crypting.encryptMessage(userskey.enc_key, new_form.notes)
            new_form.save()
        return redirect('mainapp:passwords')
    else:
        form = UserPasswordsForm()
    context = {'form':form, 'use_pass':use_pass, 'user_key':user_key}
    return render(request, 'mainapp/passwords.html', context)

def password_view(request, id):
    use_pass = UserPasswords.objects.get(id=id)
    context ={
        'use_pass':use_pass
    }
    return render(request,'mainapp/encrypted-password-view.html', context)

def decrypt_password(request, id):
    use_pass = UserPasswords.objects.get(id=id)
    user_key = UsersEncryptionKey.objects.get(user__id = request.user.id)
    site_pass = crypting.decryptMessage(user_key.enc_key, use_pass.site_password)
    the_notes = crypting.decryptMessage(user_key.enc_key, use_pass.notes)
    context = {
        'site_pass':site_pass,
        'the_notes':the_notes,
        'use_pass':use_pass
    }
    return render(request, 'mainapp/decrypted-password-view.html', context)


def notes_view(request):
    notes = UserNotes.objects.filter(user=request.user)
    user_key = UsersEncryptionKey.objects.get(user__id=request.user.id)
    if request.method == 'POST':
        form = UserNotesForm(request.POST or None)
        userskey = UsersEncryptionKey.objects.get(id = request.user.id)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.user.id = request.user.id
            new_form.note_content = crypting.encryptMessage(userskey.enc_key, new_form.note_content)
            new_form.save()
        return redirect('mainapp:notes')
    else:
        form = UserNotesForm()
    context = {'form':form, 'notes':notes, 'user_key':user_key}    
    return render(request, 'mainapp/notes.html', context)

def note_view(request, id):
    use_note = UserNotes.objects.get(id=id)
    context ={
        'use_note':use_note
    }
    return render(request,'mainapp/encrypted-note-view.html', context)

def decrypt_note(request, id):
    use_note = UserNotes.objects.get(id=id)
    user_key = UsersEncryptionKey.objects.get(user__id = request.user.id)
    the_notes = crypting.decryptMessage(user_key.enc_key, use_note.note_content)
    context = {
        'the_notes':the_notes,
        'use_note':use_note
    }
    return render(request, 'mainapp/decrypted-note-view.html', context)





def set_encryption_key(request):
    if request.method == 'POST':
        form = UsersEncryptionKeyForm(request.POST or None)
        spacing = ' '
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.user.id = request.user.id
            new_form.save()
        return redirect('mainapp:homepage')
    else:
        form = UsersEncryptionKeyForm()
    context = {
        'form':form
    }
    return render(request, 'mainapp/set-encryption.html', context)
def settings_view(request):
    enkeys = UsersEncryptionKey.objects.filter(user = request.user.id)
    context = {
        'enkeys':enkeys
    }
    return render(request, 'mainapp/keys.html', context)

def change_encryption_key(request, enc_id):
    old_enc_key = get_object_or_404(UsersEncryptionKey, id=enc_id)
    print(old_enc_key.enc_key)
    userpass = UserPasswords.objects.filter(user__id = request.user.id)
    usernotes = UserNotes.objects.filter(user__id = request.user.id)
    # userkey = .objects.get(user__id=request.user.id)
    
    if request.method == 'POST':
        form = UsersEncryptionKeyForm(request.POST, instance=old_enc_key)
        # spacing = ' '
        if form.is_valid():
            new_form = form.save(commit=False)

            for usepass in userpass:
                dec_notes = crypting.decryptMessage(old_enc_key.enc_key, usepass.notes)
                enc_notes = crypting.encryptMessage(new_form.enc_key, dec_notes)
                usepass.notes = enc_notes
                dec_site_pass = crypting.decryptMessage(old_enc_key.enc_key, usepass.site_password)
                enc_site_pass = crypting.encryptMessage(new_form.enc_key, dec_site_pass)
                usepass.site_password = enc_site_pass
                usepass.save()

            for usenote in usernotes:
                dec_note =crypting.decryptMessage(old_enc_key.enc_key, usenote.note_content)
                enc_note = crypting.encryptMessage(new_form.enc_key, dec_note)
                usenote.note_content = enc_note
                usenote.save()
            
            new_form.user = request.user
            new_form.user.id = request.user.id
            time.sleep(5)
            new_form.save()
        return redirect('mainapp:homepage')
    else:
        form = UsersEncryptionKeyForm(instance=old_enc_key)
    context = {
        'form':form,
        'key':old_enc_key
    }
    return render(request, 'mainapp/change-encryption.html', context)

class MySignUpView(SignupView):
    template_name = 'mainapp/signup.html'


class MyLoginView(LoginView):
    template_name = 'mainapp/login.html'

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>OnePass</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">


</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container">
      <div class="header-container d-flex align-items-center">
        <div class="logo mr-auto">
          <h1 class="text-light"><a href="index.html"><span>OnePass</span></a></h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav class="nav-menu d-none d-sm-block mr-auto">
          <ul>
            <li><a href="{% url 'mainapp:homepage' %}"><i class="icofont-ui-home"></i>&nbsp;Home</a></li>
            <li><a href="{% url 'mainapp:passwords' %}"><i class="icofont-ui-lock"></i>&nbsp;Passwords</a></li>
            <li><a href="{% url 'mainapp:notes' %}"><i class="icofont-ui-note"></i>&nbsp;Notes</a></li>
            <li><a href="{% url 'mainapp:settings' %}"><i class="icofont-gear"></i>&nbsp;Settings</a></li>
          </ul>
        </nav><!-- .nav-menu -->
      </div><!-- End Header Container -->
    </div>
  </header><!-- End Header -->
{% block content %}
  
{% endblock content %}

  <!-- Vendor JS Files -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/jquery.easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'vendor/waypoints/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'vendor/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

mainapp/templates/mainapp/change-encryption.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<br><br><br><br><br><br><br>
<div class="container">
    <h3 class="text-center">Use this form to change your Encryption Key</h3><br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    <div class="row">
        <div class="col-3 mx-auto">
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <input type="submit" value="Update" class="btn btn-info">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/decrypted-note-view.html
{% extends "mainapp/base.html" %}

{% block content %}
<br><br><br><br><br><br>
<div class="container">
    <p class="text-success">DECRYPTED</p>
    <p>Note Title: {{use_note.note_title}}</p>
    <p>Note Content: {{the_notes}}</p>
    <br><br>
</div>

{% endblock content %}

mainapp/templates/mainapp/decrypted-password-view.html
{% extends "mainapp/base.html" %}

{% block content %}
<br><br><br><br><br><br>
<div class="container">
    <p class="text-success">DECRYPTED</p>
    <p>URL: {{use_pass.URL}}</p>
    <p>Name: {{use_pass.name}}</p>
    <p>Username or Email: {{use_pass.username_or_email}}</p>
    <p>Site Password: {{site_pass}}</p>
    <p>Notes: {{the_notes}}</p>
    <br><br>
</div>

{% endblock content %}

mainapp/templates/mainapp/encrypted-note-view.html
{% extends "mainapp/base.html" %}

{% block content %}
<br><br><br><br><br><br>
<div class="container">
    <p class="text-danger">ENCRYPTED</p>
    <p>Note Title: {{use_note.note_title}}</p>
    <p>Note Content: {{use_note.note_content}}</p>
    <br><br>
    <a href="{% url 'mainapp:decrypt-note' use_note.id %}"><button class="btn btn-primary">Decrypt</button></a>
</div>

{% endblock content %}

mainapp/templates/mainapp/encrypted-password-view.html
{% extends "mainapp/base.html" %}

{% block content %}
<br><br><br><br><br><br>
<div class="container">
    <p class="text-danger">ENCRYPTED</p>
    <p>URL: {{use_pass.URL}}</p>
    <p>Name: {{use_pass.name}}</p>
    <p>Username or Email: {{use_pass.username_or_email}}</p>
    <p>Site Password: {{use_pass.site_password}}</p>
    <p>Notes: {{use_pass.notes}}</p>
    <br><br>
    <a href="{% url 'mainapp:decrypt-password' use_pass.id %}"><button class="btn btn-primary">Decrypt</button></a>
</div>

{% endblock content %}

mainapp/templates/mainapp/index.html
{% extends "mainapp/base.html" %}


{% block content %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex align-items-center">
    <div class="container text-center position-relative" data-aos="fade-in" data-aos-delay="200">
    <h1>Your own Private Password Manager</h1>
    <h2>Encrypt your passwords and personal notes</h2>
    {% if not user.is_authenticated %}
        <a href="{% url 'account_signup' %}" class="btn-get-started">Get Started</a>
    {% else %}
    
    {% if user_key %}
    <a href="{% url 'mainapp:passwords' %}" class="btn-get-started">Add a Password</a><br>
    {% else %}
    <p>Start by setting your encryption key <a href="{% url 'mainapp:set-encryption' %}">here</a></p>  
    {% endif %}
    
    {% endif %}
    </div>
</section><!-- End Hero -->

{% endblock content %}

mainapp/templates/mainapp/keys.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br><br><br><br><br><br>

<div class="container"> 
        {% for item in enkeys %}
        <p>Your Encryption Key is <b>{{item.enc_key}}</b></p><br>
        <p><a href="{% url 'mainapp:change-key' item.id %}">You can change it here</a></p>
        {% endfor %}
</div>  

{% endblock content %}

mainapp/templates/mainapp/notes.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br><br><br><br><br><br>
{% if user_key %}
<div class="container">
    <p>
        <a class="btn btn-success" data-toggle="modal" data-target="#passwordModal">Add a Note</a>
    </p>
</div>
<br>
<div class="modal fade" id="passwordModal" tabindex="-1" aria-label="passwordModalLabel" aria-hidden="true">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="model-header">
                    <h5 class="modal-title pl-3 pt-3" id="passwordModalLabel">Add a Note</h5>
                    <button type="button" class="close pr-3" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row row-grid align-items-center mb-2 mb-md-4">
                    <!--<div class="col-12 col-md-12 order-md-2">-->
                        <br>
                        <div class="col-12 mx-auto">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-12">{{form.note_title|as_crispy_field}}</div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">{{form.note_content|as_crispy_field}}</div>
                            </div>
                            
                            <input type="submit" class="btn btn-primary animate-up-2" value="Submit">
                        </form>
                        </div>
                    <!--</div>-->
                </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <!-- <button type="button" class="btn btn-primary"></button> -->
                </div>
            </div>
    </div>
</div>

<div class="container"> 
    <div class="card-deck">
        {% for item in notes %}
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 card-group">
            <div class="card mt-5" style="border-radius:15px;">
                <a href="{% url 'mainapp:note' item.id %}" class="pt-4 pb-4" style="background-color: purple;">
                    <!-- <img src="" class="card-img-top"> -->
                    <center>
                        <i class="icofont-ui-note" style="font-size:50px;color: white;"></i>
                    </center>
                </a>
                <div class="card-body bg-white" style="border-radius:0 0 15px 15px;box-shadow: 0 15px 12px rgba(0, 0, 0, 0.2)">
                    <h5 class="card-title"><a href="{% url 'mainapp:note' item.id %}">{{item.note_title}}</a></h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% else %}
<p class="text-center">Start by setting your encryption key <a href="{% url 'mainapp:set-encryption' %}">here</a></p>  
{% endif %}

{% endblock content %}

mainapp/templates/mainapp/passwords.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br><br><br><br><br><br>

{% if user_key %}
<div class="container">
    <p>
        <a class="btn btn-success" data-toggle="modal" data-target="#passwordModal">Add a Password</a>
    </p>
</div>
<div class="modal fade" id="passwordModal" tabindex="-1" aria-label="passwordModalLabel" aria-hidden="true">
    <div class="modal-dialog">
            <div class="modal-content">
                <div class="model-header">
                    <h5 class="modal-title pl-3 pt-3" id="passwordModalLabel">Add a Password</h5>
                    <button type="button" class="close pr-3" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row row-grid align-items-center mb-2 mb-md-4">
                    <!--<div class="col-12 col-md-12 order-md-2">-->
                        <br>
                        <div class="col-12 mx-auto">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-6">{{form.URL|as_crispy_field}}</div>
                                <div class="form-group col-md-6">{{form.name|as_crispy_field}}</div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">{{form.username_or_email|as_crispy_field}}</div>
                                <div class="form-group col-md-6">{{form.site_password|as_crispy_field}}</div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">{{form.notes|as_crispy_field}}</div>
                            </div>
                            
                            <input type="submit" class="btn btn-primary animate-up-2" value="Submit">
                        </form>
                        </div>
                    <!--</div>-->
                </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <!-- <button type="button" class="btn btn-primary"></button> -->
                </div>
            </div>
    </div>
</div>

<br>

<div class="container"> 
    <div class="card-deck">
        {% for item in use_pass %}
        <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 card-group">
            <div class="card mt-5" style="border-radius:15px;">
                <a href="{% url 'mainapp:password' item.id %}" class="pt-4 pb-4" style="background-color: cornflowerblue;">
                    <!-- <img src="" class="card-img-top"> -->
                    <center><i class="icofont-lock" style="font-size:50px;color: white;"></i></center>
                </a>
                <div class="card-body bg-white" style="border-radius:0 0 15px 15px;box-shadow: 0 15px 12px rgba(0, 0, 0, 0.2)">
                    <h5 class="card-title"><a href="{% url 'mainapp:password' item.id %}">{{item.name}}</a></h5>
                    <p class="card-text">{{item.username_or_email}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>  

{% else %}
<p class="text-center">Start by setting your encryption key <a href="{% url 'mainapp:set-encryption' %}">here</a></p>  
{% endif %}

{% endblock content %}

mainapp/templates/mainapp/set-encryption.html
{% extends "mainapp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<br><br><br><br><br><br><br>
<div class="container">
    <h3 class="text-center">Use this form to set your Encryption Key</h3><br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    <div class="row">
        <div class="col-3 mx-auto">
            <form method="POST">
                {% csrf_token %}
                
                {{form|crispy}}
                <br>
                <input type="submit" class="btn btn-success">
            </form>
        </div>
    </div>
</div>
{% endblock content %}